### ISSUE TITLE
Different path for ec2.yml

### ISSUE THREAD

**Issue by radutopala** [forward/capify-ec2#60]
Is there a way to load `ec2.yml` from a different path that the default one `config/ec2.yml`?

**Comment by edhgoose** [comment]
I've had success running the following in my deploy.rb before calling ec2_roles:

    set :ec2_config, 'location/of/my/ec2.yml'

That seems to work fine, in case anyone else has the same question.

**Comment by Rylon** [comment]
Ah my bad, I wasn't sure if that would be accessible from the `deploy.rb` without making changes. Thanks, I'll update the documentation accordingly.

**Comment by Rylon** [comment]
Updated the Readme :)
